((("1492" "1502")
  "Columbus leads expeditions to the “New World,” where he and his ships seeking a passage to trade ports in India establish colonies in the Antilles/Caribbean. In the pursuit of gold, Columbus and the colonists enslave and terrorize Indigenous inhabitants across the Antilles/Caribbean.")
 ("1493"
  "Papal decrees establish that Catholic monarchs may claim the “New World” as part of their sovereign territory and dominion over peoples living there.")
 (("1500s" "1888")
  "Britain, Denmark, France, the Netherlands, Portugal, and Spain colonize the Antilles/Caribbean, Turtle Island/North America, and Central and Southern Americas. Indigenous peoples are enslaved and killed, but also resist, trade, and move in relation to European empires. European empires, the United States, and later independent Caribbean and Latin American states establish plantation economies relying on enslaved Black labor. Up to the abolishing of the slave trade, European empires capture and transport approximately 15 million Indigenous people from Africa, primarily to the Caribbean and Latin America. The capital generated by the slave trade and plantation economy fuels Europe’s industrial revolution.")
 ("1676"
  "British settlers in Virginia led by Nathaniel Bacon revolt against the Governor in order to drive out local Doeg (Algonquian) Indians. During the rebellion, indentured Europeans and enslaved Africans united, provoking elites to enact the strict Virginia Slave Codes in 1705 to divide the colonial labor force by the racial status of inheritable enslavement.")
 ("1763"
  "Following France’s loss of the Seven Years War/French and Indian War to Britain in 1763, Britain gains the Ohio territories around the Great Lakes region, and attempts to make Native peoples of those territories subjects of British rule. To forestall Native wars, Britain passes the 1763 Royal Proclamation, forbidding the purchase of Indian lands and British settlement past the Appalachian Mountains. Elite land speculators from Southern colonies, including George Washington and Thomas Jefferson, begin to build opposition to British rule.")
 (("1763" "1766")
  "A confederation of Native warriors from numerous tribes begin Pontiac’s War against the British settlers and government, capturing military forts and taking back territory claimed by settlers. After two British military expeditions retake many of the forts, the fighting reaches a stalemate and the British government makes concessions to end the conflict, though does not give up claim to the Ohio territories.")
 (("1776" "1791")
  "The American Revolution ends with independence from Britain, and the Constitution of the United States lays the foundation of the new government, including the enslavement of African-descendant peoples. The new government rejects the British Proclamation of 1763 as a basis for Indigenous sovereignty.")
 ("1787"
  "United States Northwest Ordinance opens land for white settlement in allotments, provoking Indigenous resistance.")
 (("1791" "1804")
  "Toussaint L’ouverture leads the Haitian Revolution against French plantation rule, which ends in the establishment of Haiti as an independent republic.")
 ("1803"
  "Thomas Jefferson approves the Louisiana Purchase, purchasing from France land west of the Mississippi River to the Rocky Mountains.")
 ("1804"
  "Lewis and Clark venture into Oceti Sakowin territory on the Missouri River on an army expedition to map and expand United States territorial claims. After refusing to pay tribute for their passage, they are rebuffed by the Oceti Sakowin. The US explorers take hostage two headmen—Black Buffalo and Buffalo Medicine— to secure their passage on the river and label the Oceti Sakowin “the vilest miscreants of the savage race.”")
 (("1812" "1815")
  "United States declares war with Britain in part to move beyond established western boundaries of the new nation-state. In the Northwest, Shawnee brothers Tecumseh and Tenskwatawa form a confederacy and ally with the British. The treaty of Ghent establishes firm borders between British Canada and the United States, ignoring Native land claims. The end of the war marks the last time a European or American state forms an alliance with a Native nation or confederacy.")
 ("1815"
  "No longer checked by British competition, the United States begins removing Indians to western lands.")
 ("1816"
  "Congress restricts licenses for trade with Indians to American citizens, effectively preventing foreign trade relations with European empires.")
 ("1823"
  "The John Marshall Supreme Court, in its first decision on nation-to-nation relations with North American indigenous peoples, rules that “Indians had no right of soil as sovereign, independent states.”")
 ("1824"
  "The Bureau of Indian Affairs is created within War Department of the Executive Branch.")
 ("1831"
  "The John Marshall Supreme Court issues a second decision that “Indian tribes” are “domestic dependent nations.”")
 ("1832"
  "The John Marshall Supreme Court issues a third decision that the United States federal government, through the commerce clause of the Constitution, had the authority to govern relations between indigenous nations and states.")
 ("1835"
  "After the discovery of gold in Georgia, the state of Georgia pressures the Cherokee to move westward. The Treaty of New Echota provides the legal basis of Cherokee removal, though not approved by Cherokee National Council or Principal Chief.")
 (("1836" "1839")
  "The United States Army forcibly removes Cherokee along the “Trail of Tears.”")
 (("1836" "1840")
  "A smallpox epidemic in the Missouri Basin carried by American fur traders spreads to the Blackfoot, Assiniboine, Arikara, Crow, and Pawnee.")
 (("1846" "1848")
  "The Mexican-American War and Treaty of Guadalupe Hidalgo ceded land east and north of the Rio Grande to the United States. Article XI of the Treaty stipulates that the United States must secure the new frontier lands against Indian raids, targeting Apache and Comanche who resisted both Mexican and United States expansion. Between 1850 and 1912 the Mexican Cession land is turned into ten new states.")
 ("1848" "Gold discovered in California, settlers scramble West.")
 ("1849"
  "Department of Interior is created and adopts the Bureau of Indian Affairs from the War Department.")
 ("1851"
  "Treaty of Traverse des Sioux signed by the United States and the Dakota nations of what was Minnesota Territory. The treaty, although broken by the United States, stipulated Dakota peoples would live sedentary, agricultural lifestyles apart from white settlers and adopt Christianity in exchange for government rations and annuities for ceded lands.")
 ("1851"
  "First Fort Laramie Treaty (the Horse Creek Treaty) signed by the United States and representatives of Arapaho, Arikara, Assiniboine, Cheyenne, Crow, Hidatsa, Mandan, and Sioux nations to guarantee safe passage of settlers to California in exchange for goods and services. Ten to fifteen thousand gathered in what is the largest gathering of Plains Nations in history. Many nations never receive payment from the United States. (See Map)")
 ("1852"
  "California passes bounty law for Indian scalps, encouraging settlers to kill local indigenous people.")
 ("1861"
  "The Civil War begins, leading to an increasing professionalization of the United States army. Native nations and forces fight for both the Union and Confederacy in order to preserve their lands and sovereignty.")
 ("1862"
  "The Homestead Act opens 270 million acres of land west of the Mississippi for settlement. Settlers who lived on the land for five years, improved it, and filed an application were given ownership of the land.")
 ("1862 – 1864"
  "Dakota frustrated by the lack of payments from the federal government, settler encroachments onto Dakota land, and other treaty violations begin the Great Sioux Uprising. Bands of Dakota attack settlers, and the United States Army is called in to protect them. United States military tribunals charge 303 Dakota of murder or rape of civilians and 38 Dakota men are sentenced to deathin the largest penal execution in American history. The following year, the Bureau of Indian Affairs abolishes the Dakota reservation and forcibly moves the Dakota to Nebraska and South Dakota.")
 ("1863"
  "The transcontinental railroad begins construction between Council Bluffs, Iowa and Sacramento, California – almost all of it on land controlled by Indigenous people.")
 ("1864"
  "The Colorado Volunteer Cavalry destroy a Cheyenne and Arapaho village in Southern Colorado, killing more than a hundred, and display the maimed and disfigured bodies as trophies.")
 ("1864"
  "Union Army Captain Kit Carson begins total war against the Navajo, destroying orchards, livestock, and Hogans. Carson forces the Navajo from eastern Arizona and western New Mexico to march 300 miles without aid to Fort Sumner/Bosque Redondo. There, they are interned with little support, vulnerable to weather and raids, until allowed to return to a portion of their homelands in 1868.")
 ("1865"
  "The Civil War ends with surrender of the Confederacy. There is an increasing need for land as slavery becomes outlawed and migration to large Northern cities increases the national population. The 14th Amendment provides citizenship for Black and white people born within the United States.")
 ("1868"
  "The Fort Laramie Treaty guarantees Sioux reservation land including the Black Hills, and hunting rights in Montana, Wyoming, and South Dakota. (See Map)")
 ("1871"
  "The Indian Appropriation Act is passed with an amendment ending treaty making with Native nations – the United States moves to deal with Native nations as internal minorities rather than sovereign nations.")
 (("1876" "1877")
  "The Great Sioux War begins after gold is discovered in Black Hills and settlers rush to the area, prompting the United States Army to violate the 1868 Fort Laramie Treaty. Colonel Custer attacks Sioux and seizes the Black Hills. During the Battle of Greasy Grass (Little Bighorn), Lakota, Northern Cheyenne, and Arapaho forces kill Custer and a large portion of the U.S. 7th Cavalry.")
 ("1877"
  "The United States Army is directed to kill buffalo, which are a threat to the railroad and cattle industries as well as a primary resource for Plains nations.")
 ("1877"
  "The Black Hills Act (also known as “the Agreement of 1877,” the “Sell or Starve Act,” or the Indian Appropriations Act of 1876) cuts off government rations until the Oceti Sakowin cease hostilities and cede the Black Hills. The Black Hills were ceded but there is no record that the United States purchased the land.")
 ("1883"
  "The United States Supreme Court rules in <i>Ex Parte Crow Dog</i> that, unless Congress authorizes it, federal courts have no jurisdiction over offenses tried at the tribal councils for Indian on Indian crimes. This decision began the plenary power doctrine used to limit Indigenous sovereignty (See 1885 Major Crimes Act).")
 ("1884"
  "In<i>Elk v. Wilkins</i>, the United States Supreme Court holds the 14th Amendment’s guarantee of citizenship to all persons born in the U.S. does not apply to Indians, even those born within geographic confines of U.S.")
 ("1885"
  "TheMajor Crimes Act establishes major Indian on Indian crimes committed in Indian Country fall under federal jurisdiction and are prosecutable by federal courts. The initial seven were murder, manslaughter, rape, assault with intent to kill, arson, burglary, and theft of personal property. In addition, eight more were added, to include kidnapping, maiming, sexual abuse, incest, assault with a dangerous weapon, assault against a minor, child abuse or neglect, and robbery.")
 ("1887"
  "The Dawes Act grants the President authority to survey and divide Indian tribal reservation lands held in trust by the federal government and sell them to individual Indians. Those who accepted allotments and lived separately from tribes would be granted U.S. citizenship.")
 ("1889"
  "United States violates the 1868 Fort Laramie Treaty by breaking up the Great Sioux Reservation into five smaller reservations, enforcing private property ownership, agriculture, and residential schools without adequate resources. (See Map)")
 ("1890"
  "In response to the United States breaking up of the Great Sioux Reservation, Lakota Sioux take up the Ghost Dance. The Bureau of Indian Affairs calls in the Army, which assassinates Crazy Horse and Sitting Bull. A small band of Lakota is forced to camp outside Pine Ridge Reservation at Wounded Knee Creek, where the army attempts to disarm them. The U.S. army escalates a confrontation and kills 250 to 300 Lakota, mostly women and children.")
 ("1908"
  "In<i>Winters v. United States</i>, the United States Supreme Court clarifies Indian reservation rights to water by ruling that Indian reservations have water use rights that cannot be blocked through water projects.")
 ("1921"
  "Congress passes the Snyder Act, allowing appropriation of money for Indians (regardless of blood quantum/residence) under broad authority given to the Secretary of the Interior. This greatly expands funds for Indians by releasing the federal government from a strict adherence to treaty provisions.")
 ("1924"
  "Indians are unilaterally made citizens of the United States, furthering the project of assimilating Native nations into the United States rather than recognizing their sovereignty.")
 ("1934"
  "Indian Reorganization Act ends allotment and replaces traditional governance structures with Western, electoral system and tribal constitutions modeled after the United States Constitution.")
 ("1944"
  "Indian Claims Commission is set up to settle outstanding claims against the United States. Generally viewed as the beginning of the termination era.")
 ("1944"
  "Congress passes the Pick-Sloan Missouri Basin Plan, a massive water infrastructure project meant to increase hydropower, navigability, fishing and wildlife, and recreation along the Missouri River and its tributaries. In building these projects, the Army Corps of Engineers violates the Fort Laramie Treaties and Winters doctrine supporting the sovereignty of tribal lands, consultation, and access to water.")
 ("1944"
  "National Congress of American Indians is established (Denver, Colorado) in anticipation of federal termination and assimilation policies in order to resist the elimination of tribal status.")
 ("1945"
  "President Truman enters office and directs the Bureau of Indian Affairs to focus on termination and the assimilation of Indians into American Cold War society. From 1945-1960 the federal government terminates over 100 tribes and bands.")
 ("1948"
  "Construction begins on the Lake Oahe dam for the Pick-Sloan Missouri Basin Program, and is completed in 1962. The Lake Oahe dam destroys more Native land than any other water project in the United States, and eliminates 90% of timber land on the Standing Rock Sioux and Cheyenne Sioux Reservations, along with grazing and agricultural land.")
 ("1949"
  "The Hoover Commission recommends “termination” of Native reservations, and assimilation of Indians into American cities and society, reversing the Roosevelt New Deal policies and returning to 19th century politics of assimilation.")
 ("1952"
  "House Joint Resolution 698 establishes criteria and guidelines for the termination of trustee status of Indian tribes and reservations. This is followed by several standalone termination resolutions, some of which immediately terminated dozens of tribes.")
 ("1953"
  "Public Law 280 moves authority and jurisdiction over tribal lands and resources from the Bureau of Indian Affairs to the states in which tribes and reserves are located.")
 ("1961"
  "Over 200 tribes gather in Chicago at the American Indian Chicago Conference. The Declaration of Indian Purpose is drafted for submission to Congress.")
 ("1961"
  "From the Chicago Conference, the National Indian Youth Council is formed in Gallup, New Mexico, beginning the Red Power Movement.")
 ("1968"
  "Congress passes the American Indian Civil Rights Act (loosely modeled on the protection the U.S. Constitution provides against state and local governments). It provides individual Indians with some statutory protection against their tribal governments.")
 ("1969"
  "Occupation of Alcatraz by American Indian Movement to reclaim traditional land. Simultaneously, sit-ins are staged at the offices of the BIA.")
 (("1960" "1979") " Creation of tribal colleges.")
 ("1970"
  "In a special message to Congress on Indian Affairs, President Richard Nixon calls for the repeal of termination laws and the inauguration of the era of self-determination through self-help and community programming.")
 ("1971"
  "The Alaska Natives Claims Settlement Act is passed. This saw 90% of Alaska Natives’ land claims exchanged for a guarantee of 44 million acres and $1 billion.")
 ("1972"
  "Trail of Broken Treaties Caravan. Several Indigenous-led groups (close to 200 Indians in total) began caravaning from the West coast to Washington D.C. to present President Nixon with a 20-point position paper demanding the United States respect the sovereignty of Indian nations. After Nixon refuses to meet with the Caravan, they occupy the Bureau of Indian Affair headquarters for a week until Nixon aides agreed to treaty negotiations.")
 ("1973"
  "Wounded Knee Occupation. Oglala Lakota and American Indian Movement members occupy the town of Wounded Knee in the Pine Ridge Indian Reservation to protest against the corrupt reserve governance structure. The Occupation lasts for 71 days and calls for re-establishment of United States treaty obligations and nation-to-nation relations with Indian nations in the United States. AIM member Leonard Peltier is held in federal prison for the murder of two FBI agents despite evidence that his trial was unconstitutional and unfair.")
 ("1974"
  "First meeting of the International Indian Treaty Council, the international arm of AIM, meets in Standing Rock Indian Reservation. More than 2000 people from 90 Indigenous Nations attend and issue “The Declaration for Continuing Independence.”")
 ("1975"
  "The Indian Self-Determination and Education Act is passed. Tribal governments get more control over their tribal affairs and can appropriate more funds for education.")
 ("1978"
  "In <i>Oliphant v. Squamish Indian Tribe</i>, the United States Supreme Court reverses lower court decisions and decides that Indian tribes do not have jurisdiction over non-Natives on tribal or reservation land.")
 ("1980"
  "U.S. government rules that the U.S. illegally seized the Black Hills in 1877, and offers $15.5 million (1877 price of the land) plus $105 million (5% interest on the land over 103 years). The Lakota refuse and demand return of land from the United States.")
 ("1980"
  "The Penobscots and Passamaquoddies accept monetary compensation from the US Government for their lands (now the state of Maine), which the Massachusetts government took illegally in 1970.")
 ("1986"
  "Congress amends the Indian Civil Rights Act and grants tribal courts the power to impose criminal penalties.")
 ("1988" "Congress officially repeals the Termination Policy.")
 ("1993"
  "Ada Deer is appointed Assistant Secretary for Indian Affairs by President Bill Clinton. She is the first Indian woman to hold the position.")
 ("1994"
  "Three hundred representatives from the 556 federally recognized tribes meet with President Bill Clinton. This is the first time since 1822 that Indians have been invited to officially meet with a US President to discuss Indian affairs.")
 ("1994"
  "The Violence Against Women Act is passed, which does not have provisions for tribal prosecution of domestic and sexual crimes against Native women by non-Native men.")
 ("1996"
  "The University of Arizona creates the first PhD program in American Indian Studies.")
 ("1998"
  "Four thousand Alaska Natives march in Anchorage in protest of Alaska legislative and legal attacks on tribal governments and Native hunting and fishing traditions.")
 ("1998"
  "President Clinton issues Executive Order No.13084 (“Consultation and Coordination with Indian Tribal Governments”). This pledges that the federal government will establish and uphold meaningful consultation and collaboration with Indian tribal governments in matters that will significantly impact their communities.")
 ("1998"
  "The Makah Nation of Washington State renews its traditional practice of whaling after a respite of seventy years, despite protests from many environmentalists and other groups.")
 ("1999"
  "President Clinton visits the Pine Ridge Sioux Reservation in South Dakota. He is the first sitting President since Calvin Coolidge in 1927 to make an official visit to an Indian Reservation.")
 ("2000"
  "The United States Supreme Court declines to review a religious freedom case centering around the use of Devils Tower in Wyoming, a sacred site to several Indian nations. This decision upholds a federal court ruling that supported the religious rights of Indians against challenges from recreational rock climbers.")
 ("2002"
  "In a blow to the Makah Nation, the 9th U.S. Circuit Court of Appeals rules in Anderson v. Evans, in a case brought by animal advocacy groups, that the government had violated the National Environmental Policy Act by failing to prepare an environmental impact statement prior to approving the whaling quota and also held that the Marine Mammal Protection Act applied to the tribe’s proposed whale hunt.")
 ("2002"
  "President Bush signs an executive order reaffirming the federal government’s commitment to tribally-controlled colleges and universities.")
 ("2004"
  "In <i>United States v. Lara </i>the Supreme Court holds that tribal courts had the inherent sovereign power to criminally prosecute nonmember Indians and that such power did not violate the U.S. Constitution’s Fifth Amendment double jeopardy clause.")
 ("2004"
  "In <i>Boneshirt v. Hazeltine</i>, a Federal district court rules that South Dakota violated the 1965 federal Voting Rights Act when it approved a statewide redistricting plan that had the effect of diluting the voting power of Indians in two districts.")
 ("2006"
  "Congress enacts the Esther Martinez Native American Languages Preservation Act of 2006 (PL 109-394) to ensure the survival and continuing vitality of Native American languages.")
 ("2007"
  "The United Nations adopts the Declaration on the Rights of Indigenous Peoples. The United States, Canada, New Zealand, and Australia vote against the Declaration’s adoption.")
 ("2008"
  "The Supreme Court in <i>Plains Commerce Bank</i><i>v. Long Family Land and Cattle Company Inc</i>. holds that tribal courts lack jurisdiction to decide a discrimination claim concerning a non-Indian bank’s sake of fee land that it owned within a reservation.")
 ("2009"
  "President Obama signs a presidential memorandum seeking to renew and enhance the spirit of tribal consultation and collaboration previously outlined by the Clinton administration.")
 ("2010"
  "The North Dakota Supreme Court supports a Board of Higher Education decision to retire the University of North Dakota’s Fighting Sioux nickname and logo.")
 ("2012"
  "HEARTH Act allows tribal governments to approve leasing of tribal lands: The Helping Expedite and Advance Responsible Tribal Home Ownership Act of 2012 (the HEARTH Act) creates a voluntary, alternative land leasing process available to tribes by amending the Indian Long-Term Leasing Act of 1955, 25 U.S.C. Sec. 415.")
 ("2012"
  "The Oglala Sioux Tribe of South Dakota sued some of the world’s largest beer makers for $500 million claiming they knowingly contributed to alcohol-related problems on the Pine Ridge Indian Reservation.")
 ("2013"
  "The Violence Against Women Act is reauthorized, and includes provisions where tribal governments may prosecute non-Natives, but only those who are accused of sexual or domestic violence against Natives with whom they have intimate relationships or other close ties. The legislation excludes Alaska Natives.")
 ("2013"
  "Members of Congress took part in a ceremony bestowing the Congressional Gold Medal to honor 33 tribes for their WWI and WWII contributions as code talkers.")
 ("2014"
  "President Obama speaks at the Standing Rock Sioux Reservation in North Dakota promoting the need to help reservations create jobs. At the time, some 63% of able workers at Standing Rock were unemployed on the 2.3 million-acre reservation, which is home to some 850 residents.")
 ("2015"
  "In February, the US Army Corps of Engineers (USACE), the federal government body in charge of the nation’s waterways, initiates the Dakota Access Pipeline Project. By December, The Corps publishes an environmental assessment stating that “the Standing Rock THPO had indicated to DAPL that the Lake Oahu site avoided impacts to tribally significant sites.” The Corps eventually receives critical letters on the assessment from the Environmental Protection Agency, the US Department of Interior, and the American Council on Historical Preservation (ACHP). Other tribes whose ancestral lands are slated to be crossed by the pipeline voice their concerns in solidarity with Standing Rock, including the Osage Nation and Iowa Tribe THPO, who wrote to the ACHP: “We have not been consulted in an appropriate manner about the presence of traditional cultural properties, sites, or landscapes vital to our identity and spiritual well-being.”")
 ("2016"
  "In August, the Standing Rock Sioux, represented by Earthjustice, file an injunction, suing the Army Corps of Engineers. Eleven days later, Energy Transfer Partners, the parent company of Dakota Access LLC, sues the Standing Rock Sioux chairman and other tribal members for blocking construction."))
